services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_tracker_front
    ports:
      - "8081:80"
    networks:
      - tracker_network

networks:
  tracker_network:
